### ISSUE TITLE
RedCookie is on Product Hunt and we need you to join the conversation!

### ISSUE THREAD

**Issue by shnbhg** [scalalang2/RedCookie#5]
Hey Dohyeon,
RedCookie is on Product Hunt and we'd like you to be listed as the maker!
Can you join the conversation on https://www.producthunt.com/posts/redcookie?

**Comment by shnbhg** [comment]
Turns out even Motty was featured!

**Comment by scalalang2** [comment]
@shnbhg Hi. Thanks for noting me. Honestly the author of that posts is me. :-)

**Comment by scalalang2** [comment]
Have a nice day!!!

**Comment by shnbhg** [comment]
I'm so sorry, didn't notice.. I was trying to find you on Twitter.. I've added you as a maker in both posts! Congrats!
